build:
  - pip install -r requirements.txt
  - python manage.py collectstatic --noinput
  - python manage.py migrate

services:
  - type: web
    name: arabtili
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: arabtili-db
          property: connectionString

databases:
  - name: arabtili-db
    databaseName: arabtili
    user: arabtili
